name: k6 API Test

on:
  workflow_dispatch:
  push:

jobs:
  k6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 test
        run: k6 run token_api_test.js
